### ISSUE TITLE
An idea!

### ISSUE THREAD

**Issue by enkriptor** [Vikka/math_adventures_with_python#1]
Hi, lets make this repository into a research repo. I mainly work into cryptography, so can share some cryptographic insight!

**Comment by Vikka** [comment]
I don't understand what you want :frowning_face:

**Comment by enkriptor** [comment]
I'm saying,
1) lets do some research together in your repository
2) i know about cryptography which might help into the researches

**Comment by Vikka** [comment]
What do you have in mind ?
Actually, it's a repo I use to store code and example from a book.
